flags: {}
packages:
- '.'
extra-deps: 
- scotty-tls-0.4.1
# resolver: nightly-2016-05-21
# resolver: lts-8.9
# resolver: nightly-2017-10-06
# resolver: lts-10.0
# resolver: lts-12.2
resolver: lts-13.20

